/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/_painel'
import { Route as TotemRouteRouteImport } from './routes/totem/route'
import { Route as DevMaquininhaRouteImport } from './routes/dev/maquininha'
import { Route as TotemIndexRouteImport } from './routes/totem/index'
import { Route as TotemAguardandoPagamentoRouteImport } from './routes/totem/aguardando-pagamento'
import { Route as TotemCardapioRouteImport } from './routes/totem/cardapio'
import { Route as TotemEnderecoRouteImport } from './routes/totem/endereco'
import { Route as TotemIdentificacaoRouteImport } from './routes/totem/identificacao'
import { Route as TotemModoEntregaRouteImport } from './routes/totem/modo-entrega'
import { Route as TotemOfertaComboRouteImport } from './routes/totem/oferta-combo'
import { Route as TotemOndeConsumirRouteImport } from './routes/totem/onde-consumir'
import { Route as TotemPagamentoRouteImport } from './routes/totem/pagamento'
import { Route as TotemPedidoRealizadoRouteImport } from './routes/totem/pedido-realizado'
import { Route as TotemRevisaoRouteImport } from './routes/totem/revisao'
import { Route as PainelPdvIndexRouteImport } from './routes/_painel/pdv/index'
import { Route as PainelPdvProdutosRouteImport } from './routes/_painel/pdv/produtos'
import { Route as PainelRelatoriosIndexRouteImport } from './routes/_painel/relatorios/index'
import { Route as ApiMaquininhaConfirmarRouteImport } from './routes/api/maquininha/confirmar'
import { Route as ApiMaquininhaPendentesRouteImport } from './routes/api/maquininha/pendentes'
import { Route as ImprimirComandaIdRouteImport } from './routes/imprimir/comanda.$id'
import { Route as ImprimirCozinhaIdRouteImport } from './routes/imprimir/cozinha.$id'
import { Route as TotemProdutoIdRouteImport } from './routes/totem/produto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/_painel',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemRouteRoute = TotemRouteRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMaquininhaRoute = DevMaquininhaRouteImport.update({
  id: '/dev/maquininha',
  path: '/dev/maquininha',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemIndexRoute = TotemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemAguardandoPagamentoRoute =
  TotemAguardandoPagamentoRouteImport.update({
    id: '/aguardando-pagamento',
    path: '/aguardando-pagamento',
    getParentRoute: () => TotemRouteRoute,
  } as any)
const TotemCardapioRoute = TotemCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemEnderecoRoute = TotemEnderecoRouteImport.update({
  id: '/endereco',
  path: '/endereco',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemIdentificacaoRoute = TotemIdentificacaoRouteImport.update({
  id: '/identificacao',
  path: '/identificacao',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemModoEntregaRoute = TotemModoEntregaRouteImport.update({
  id: '/modo-entrega',
  path: '/modo-entrega',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemOfertaComboRoute = TotemOfertaComboRouteImport.update({
  id: '/oferta-combo',
  path: '/oferta-combo',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemOndeConsumirRoute = TotemOndeConsumirRouteImport.update({
  id: '/onde-consumir',
  path: '/onde-consumir',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemPagamentoRoute = TotemPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemPedidoRealizadoRoute = TotemPedidoRealizadoRouteImport.update({
  id: '/pedido-realizado',
  path: '/pedido-realizado',
  getParentRoute: () => TotemRouteRoute,
} as any)
const TotemRevisaoRoute = TotemRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => TotemRouteRoute,
} as any)
const PainelPdvIndexRoute = PainelPdvIndexRouteImport.update({
  id: '/pdv/',
  path: '/pdv/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPdvProdutosRoute = PainelPdvProdutosRouteImport.update({
  id: '/pdv/produtos',
  path: '/pdv/produtos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelRelatoriosIndexRoute = PainelRelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => PainelRoute,
} as any)
const ApiMaquininhaConfirmarRoute = ApiMaquininhaConfirmarRouteImport.update({
  id: '/api/maquininha/confirmar',
  path: '/api/maquininha/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaquininhaPendentesRoute = ApiMaquininhaPendentesRouteImport.update({
  id: '/api/maquininha/pendentes',
  path: '/api/maquininha/pendentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirComandaIdRoute = ImprimirComandaIdRouteImport.update({
  id: '/imprimir/comanda/$id',
  path: '/imprimir/comanda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirCozinhaIdRoute = ImprimirCozinhaIdRouteImport.update({
  id: '/imprimir/cozinha/$id',
  path: '/imprimir/cozinha/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemProdutoIdRoute = TotemProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => TotemRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/totem': typeof TotemRouteRouteWithChildren
  '/dev/maquininha': typeof DevMaquininhaRoute
  '/totem/aguardando-pagamento': typeof TotemAguardandoPagamentoRoute
  '/totem/cardapio': typeof TotemCardapioRoute
  '/totem/endereco': typeof TotemEnderecoRoute
  '/totem/identificacao': typeof TotemIdentificacaoRoute
  '/totem/modo-entrega': typeof TotemModoEntregaRoute
  '/totem/oferta-combo': typeof TotemOfertaComboRoute
  '/totem/onde-consumir': typeof TotemOndeConsumirRoute
  '/totem/pagamento': typeof TotemPagamentoRoute
  '/totem/pedido-realizado': typeof TotemPedidoRealizadoRoute
  '/totem/revisao': typeof TotemRevisaoRoute
  '/totem/': typeof TotemIndexRoute
  '/pdv/produtos': typeof PainelPdvProdutosRoute
  '/api/maquininha/confirmar': typeof ApiMaquininhaConfirmarRoute
  '/api/maquininha/pendentes': typeof ApiMaquininhaPendentesRoute
  '/imprimir/comanda/$id': typeof ImprimirComandaIdRoute
  '/imprimir/cozinha/$id': typeof ImprimirCozinhaIdRoute
  '/totem/produto/$id': typeof TotemProdutoIdRoute
  '/pdv/': typeof PainelPdvIndexRoute
  '/relatorios/': typeof PainelRelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/maquininha': typeof DevMaquininhaRoute
  '/totem/aguardando-pagamento': typeof TotemAguardandoPagamentoRoute
  '/totem/cardapio': typeof TotemCardapioRoute
  '/totem/endereco': typeof TotemEnderecoRoute
  '/totem/identificacao': typeof TotemIdentificacaoRoute
  '/totem/modo-entrega': typeof TotemModoEntregaRoute
  '/totem/oferta-combo': typeof TotemOfertaComboRoute
  '/totem/onde-consumir': typeof TotemOndeConsumirRoute
  '/totem/pagamento': typeof TotemPagamentoRoute
  '/totem/pedido-realizado': typeof TotemPedidoRealizadoRoute
  '/totem/revisao': typeof TotemRevisaoRoute
  '/totem': typeof TotemIndexRoute
  '/pdv/produtos': typeof PainelPdvProdutosRoute
  '/api/maquininha/confirmar': typeof ApiMaquininhaConfirmarRoute
  '/api/maquininha/pendentes': typeof ApiMaquininhaPendentesRoute
  '/imprimir/comanda/$id': typeof ImprimirComandaIdRoute
  '/imprimir/cozinha/$id': typeof ImprimirCozinhaIdRoute
  '/totem/produto/$id': typeof TotemProdutoIdRoute
  '/pdv': typeof PainelPdvIndexRoute
  '/relatorios': typeof PainelRelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/totem': typeof TotemRouteRouteWithChildren
  '/_painel': typeof PainelRouteWithChildren
  '/dev/maquininha': typeof DevMaquininhaRoute
  '/totem/aguardando-pagamento': typeof TotemAguardandoPagamentoRoute
  '/totem/cardapio': typeof TotemCardapioRoute
  '/totem/endereco': typeof TotemEnderecoRoute
  '/totem/identificacao': typeof TotemIdentificacaoRoute
  '/totem/modo-entrega': typeof TotemModoEntregaRoute
  '/totem/oferta-combo': typeof TotemOfertaComboRoute
  '/totem/onde-consumir': typeof TotemOndeConsumirRoute
  '/totem/pagamento': typeof TotemPagamentoRoute
  '/totem/pedido-realizado': typeof TotemPedidoRealizadoRoute
  '/totem/revisao': typeof TotemRevisaoRoute
  '/totem/': typeof TotemIndexRoute
  '/_painel/pdv/produtos': typeof PainelPdvProdutosRoute
  '/api/maquininha/confirmar': typeof ApiMaquininhaConfirmarRoute
  '/api/maquininha/pendentes': typeof ApiMaquininhaPendentesRoute
  '/imprimir/comanda/$id': typeof ImprimirComandaIdRoute
  '/imprimir/cozinha/$id': typeof ImprimirCozinhaIdRoute
  '/totem/produto/$id': typeof TotemProdutoIdRoute
  '/_painel/pdv/': typeof PainelPdvIndexRoute
  '/_painel/relatorios/': typeof PainelRelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/totem'
    | '/dev/maquininha'
    | '/totem/aguardando-pagamento'
    | '/totem/cardapio'
    | '/totem/endereco'
    | '/totem/identificacao'
    | '/totem/modo-entrega'
    | '/totem/oferta-combo'
    | '/totem/onde-consumir'
    | '/totem/pagamento'
    | '/totem/pedido-realizado'
    | '/totem/revisao'
    | '/totem/'
    | '/pdv/produtos'
    | '/api/maquininha/confirmar'
    | '/api/maquininha/pendentes'
    | '/imprimir/comanda/$id'
    | '/imprimir/cozinha/$id'
    | '/totem/produto/$id'
    | '/pdv/'
    | '/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev/maquininha'
    | '/totem/aguardando-pagamento'
    | '/totem/cardapio'
    | '/totem/endereco'
    | '/totem/identificacao'
    | '/totem/modo-entrega'
    | '/totem/oferta-combo'
    | '/totem/onde-consumir'
    | '/totem/pagamento'
    | '/totem/pedido-realizado'
    | '/totem/revisao'
    | '/totem'
    | '/pdv/produtos'
    | '/api/maquininha/confirmar'
    | '/api/maquininha/pendentes'
    | '/imprimir/comanda/$id'
    | '/imprimir/cozinha/$id'
    | '/totem/produto/$id'
    | '/pdv'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/totem'
    | '/_painel'
    | '/dev/maquininha'
    | '/totem/aguardando-pagamento'
    | '/totem/cardapio'
    | '/totem/endereco'
    | '/totem/identificacao'
    | '/totem/modo-entrega'
    | '/totem/oferta-combo'
    | '/totem/onde-consumir'
    | '/totem/pagamento'
    | '/totem/pedido-realizado'
    | '/totem/revisao'
    | '/totem/'
    | '/_painel/pdv/produtos'
    | '/api/maquininha/confirmar'
    | '/api/maquininha/pendentes'
    | '/imprimir/comanda/$id'
    | '/imprimir/cozinha/$id'
    | '/totem/produto/$id'
    | '/_painel/pdv/'
    | '/_painel/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TotemRouteRoute: typeof TotemRouteRouteWithChildren
  PainelRoute: typeof PainelRouteWithChildren
  DevMaquininhaRoute: typeof DevMaquininhaRoute
  ApiMaquininhaConfirmarRoute: typeof ApiMaquininhaConfirmarRoute
  ApiMaquininhaPendentesRoute: typeof ApiMaquininhaPendentesRoute
  ImprimirComandaIdRoute: typeof ImprimirComandaIdRoute
  ImprimirCozinhaIdRoute: typeof ImprimirCozinhaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel': {
      id: '/_painel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/maquininha': {
      id: '/dev/maquininha'
      path: '/dev/maquininha'
      fullPath: '/dev/maquininha'
      preLoaderRoute: typeof DevMaquininhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem/': {
      id: '/totem/'
      path: '/'
      fullPath: '/totem/'
      preLoaderRoute: typeof TotemIndexRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/aguardando-pagamento': {
      id: '/totem/aguardando-pagamento'
      path: '/aguardando-pagamento'
      fullPath: '/totem/aguardando-pagamento'
      preLoaderRoute: typeof TotemAguardandoPagamentoRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/cardapio': {
      id: '/totem/cardapio'
      path: '/cardapio'
      fullPath: '/totem/cardapio'
      preLoaderRoute: typeof TotemCardapioRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/endereco': {
      id: '/totem/endereco'
      path: '/endereco'
      fullPath: '/totem/endereco'
      preLoaderRoute: typeof TotemEnderecoRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/identificacao': {
      id: '/totem/identificacao'
      path: '/identificacao'
      fullPath: '/totem/identificacao'
      preLoaderRoute: typeof TotemIdentificacaoRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/modo-entrega': {
      id: '/totem/modo-entrega'
      path: '/modo-entrega'
      fullPath: '/totem/modo-entrega'
      preLoaderRoute: typeof TotemModoEntregaRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/oferta-combo': {
      id: '/totem/oferta-combo'
      path: '/oferta-combo'
      fullPath: '/totem/oferta-combo'
      preLoaderRoute: typeof TotemOfertaComboRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/onde-consumir': {
      id: '/totem/onde-consumir'
      path: '/onde-consumir'
      fullPath: '/totem/onde-consumir'
      preLoaderRoute: typeof TotemOndeConsumirRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/pagamento': {
      id: '/totem/pagamento'
      path: '/pagamento'
      fullPath: '/totem/pagamento'
      preLoaderRoute: typeof TotemPagamentoRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/pedido-realizado': {
      id: '/totem/pedido-realizado'
      path: '/pedido-realizado'
      fullPath: '/totem/pedido-realizado'
      preLoaderRoute: typeof TotemPedidoRealizadoRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/totem/revisao': {
      id: '/totem/revisao'
      path: '/revisao'
      fullPath: '/totem/revisao'
      preLoaderRoute: typeof TotemRevisaoRouteImport
      parentRoute: typeof TotemRouteRoute
    }
    '/_painel/pdv/': {
      id: '/_painel/pdv/'
      path: '/pdv'
      fullPath: '/pdv/'
      preLoaderRoute: typeof PainelPdvIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/pdv/produtos': {
      id: '/_painel/pdv/produtos'
      path: '/pdv/produtos'
      fullPath: '/pdv/produtos'
      preLoaderRoute: typeof PainelPdvProdutosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/relatorios/': {
      id: '/_painel/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof PainelRelatoriosIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/api/maquininha/confirmar': {
      id: '/api/maquininha/confirmar'
      path: '/api/maquininha/confirmar'
      fullPath: '/api/maquininha/confirmar'
      preLoaderRoute: typeof ApiMaquininhaConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maquininha/pendentes': {
      id: '/api/maquininha/pendentes'
      path: '/api/maquininha/pendentes'
      fullPath: '/api/maquininha/pendentes'
      preLoaderRoute: typeof ApiMaquininhaPendentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir/comanda/$id': {
      id: '/imprimir/comanda/$id'
      path: '/imprimir/comanda/$id'
      fullPath: '/imprimir/comanda/$id'
      preLoaderRoute: typeof ImprimirComandaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir/cozinha/$id': {
      id: '/imprimir/cozinha/$id'
      path: '/imprimir/cozinha/$id'
      fullPath: '/imprimir/cozinha/$id'
      preLoaderRoute: typeof ImprimirCozinhaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem/produto/$id': {
      id: '/totem/produto/$id'
      path: '/produto/$id'
      fullPath: '/totem/produto/$id'
      preLoaderRoute: typeof TotemProdutoIdRouteImport
      parentRoute: typeof TotemRouteRoute
    }
  }
}

interface TotemRouteRouteChildren {
  TotemAguardandoPagamentoRoute: typeof TotemAguardandoPagamentoRoute
  TotemCardapioRoute: typeof TotemCardapioRoute
  TotemEnderecoRoute: typeof TotemEnderecoRoute
  TotemIdentificacaoRoute: typeof TotemIdentificacaoRoute
  TotemModoEntregaRoute: typeof TotemModoEntregaRoute
  TotemOfertaComboRoute: typeof TotemOfertaComboRoute
  TotemOndeConsumirRoute: typeof TotemOndeConsumirRoute
  TotemPagamentoRoute: typeof TotemPagamentoRoute
  TotemPedidoRealizadoRoute: typeof TotemPedidoRealizadoRoute
  TotemRevisaoRoute: typeof TotemRevisaoRoute
  TotemIndexRoute: typeof TotemIndexRoute
  TotemProdutoIdRoute: typeof TotemProdutoIdRoute
}

const TotemRouteRouteChildren: TotemRouteRouteChildren = {
  TotemAguardandoPagamentoRoute: TotemAguardandoPagamentoRoute,
  TotemCardapioRoute: TotemCardapioRoute,
  TotemEnderecoRoute: TotemEnderecoRoute,
  TotemIdentificacaoRoute: TotemIdentificacaoRoute,
  TotemModoEntregaRoute: TotemModoEntregaRoute,
  TotemOfertaComboRoute: TotemOfertaComboRoute,
  TotemOndeConsumirRoute: TotemOndeConsumirRoute,
  TotemPagamentoRoute: TotemPagamentoRoute,
  TotemPedidoRealizadoRoute: TotemPedidoRealizadoRoute,
  TotemRevisaoRoute: TotemRevisaoRoute,
  TotemIndexRoute: TotemIndexRoute,
  TotemProdutoIdRoute: TotemProdutoIdRoute,
}

const TotemRouteRouteWithChildren = TotemRouteRoute._addFileChildren(
  TotemRouteRouteChildren,
)

interface PainelRouteChildren {
  PainelPdvProdutosRoute: typeof PainelPdvProdutosRoute
  PainelPdvIndexRoute: typeof PainelPdvIndexRoute
  PainelRelatoriosIndexRoute: typeof PainelRelatoriosIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelPdvProdutosRoute: PainelPdvProdutosRoute,
  PainelPdvIndexRoute: PainelPdvIndexRoute,
  PainelRelatoriosIndexRoute: PainelRelatoriosIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TotemRouteRoute: TotemRouteRouteWithChildren,
  PainelRoute: PainelRouteWithChildren,
  DevMaquininhaRoute: DevMaquininhaRoute,
  ApiMaquininhaConfirmarRoute: ApiMaquininhaConfirmarRoute,
  ApiMaquininhaPendentesRoute: ApiMaquininhaPendentesRoute,
  ImprimirComandaIdRoute: ImprimirComandaIdRoute,
  ImprimirCozinhaIdRoute: ImprimirCozinhaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
